### ISSUE TITLE
Сделать все одной кнопкой (командой).

### ISSUE THREAD

**Issue by Ground-Zerro** [JB-SelfCompany/awg_bot#1]
В свое время делал sh [скрипт](https://github.com/Ground-Zerro/DNS-RouteSync-Navigator/blob/main/start.sh) для управления программой на python.

Можно его немного подправить под этот проект и добавить к основной инструкции в качестве альтернативы - "сделать все одной кнопкой", в т.ч.:
Проверить и скачать недостающие файл/службы/пакеты, поставить Python 3.11.x, и зависимости, активировать виртуальное окружение + установка/запуск/перезапуск/остановка/удаление и мониторинг состояния системной службы.

Вдруг пригодится идея.

**Comment by JB-SelfCompany** [comment]
Добрый день. 

Опишите, пожалуйста, как вы себе это видите. Более подробно. 
Допустим, будет скрипт install.sh. При запуске что желаете видеть? Какие функции?

Идея интересная. Если опишите желаемое, смогу реализовать.

**Comment by Ground-Zerro** [comment]
> Опишите, пожалуйста, как вы себе это видите. Более подробно.

Ну всю логику вряд-ли опишу, это не более чем "обмен опытом" ))

Linux
Пользователь копирует команду и выполняет на своем сервере (пример).
```
curl -O https://raw.githubusercontent.com/Ground-Zerro/DNS-RouteSync-Navigator/main/start.sh && chmod +x start.sh && ./start.sh
```
Скрипт проверяет
- наличие установленного себя

Бот установлен как служба, предлагается меню:
=== Отображается статус службы (запущена\нет\статус ошибки\) ===
- Остановить
- Перезапустить
- Удалить службу
- выйти

Бот не установлен:
- установить? (как службу)
- выйти

Установить как службу
- проверяется наличие необходимых компонентов в т.ч. пакетов необходимых для работы, их версий, зависимостей Python.
Информация:
(если несовместимая версия Python или его нет)
=== Пайтон имеет не совместимую версию (не установлен). Переустановить (установить)? ===
да\нет (если нет - то завершение скрипта)
- ставится python (если его нет или неверная версия).
- ставится гит.
- копируется репозиторий.
- разворачивается репозиторий.
- прописывается виртуальное окружение.
- другие необходимые манипуляции в системе.
=== Почти готово, введите код полученный от БотоОтца (возможно краткая инструкция "Как") ===
- приписывается api бота.
- служба запускается.
=== Все готово и работает ===

Удаление:
- ну и так думаю понятно..

[Пример для Linux](https://github.com/Ground-Zerro/DNS-RouteSync-Navigator/blob/main/start.sh)
[Пример для windows, делал что-то очень похожее](https://github.com/Ground-Zerro/DomainMapper/tree/main/Windows). Там же по ссылке код на выполнение в windows без загрузки на ПК (сразу из репозитория из cmd или PowerShell).


В дополнение к подробной длинной инструкции для Гиков опция для Неофитов - *одна команда и настройка мастером по текстовым подсказкам*

**Comment by Ground-Zerro** [comment]
Что-то типа такого (пример):
```
#!/bin/bash

# Название службы
SERVICE_NAME="awg_bot"

# Проверка наличия Python 3.11
check_python() {
    if python3.11 --version &>/dev/null; then
        echo "Python 3.11 установлен."
    else
        echo "Python 3.11 не установлен или версия не подходит."
        read -p "Установить Python 3.11? (y/n): " install_python
        if [[ "$install_python" == "y" ]]; then
            sudo apt-get install software-properties-common -y
            sudo add-apt-repository ppa:deadsnakes/ppa -y
            sudo apt-get update
            sudo apt-get install python3.11 python3.11-venv python3.11-dev -y
        else
            echo "Установка Python 3.11 обязательна. Завершение работы."
            exit 1
        fi
    fi
}

# Проверка наличия git
check_git() {
    if ! git --version &>/dev/null; then
        echo "Git не установлен."
        read -p "Установить git? (y/n): " install_git
        if [[ "$install_git" == "y" ]]; then
            sudo apt-get update
            sudo apt-get install git -y
        else
            echo "Git обязателен для работы. Завершение работы."
            exit 1
        fi
    else
        echo "Git установлен."
    fi
}

# Установка зависимостей
install_dependencies() {
    echo "Установка зависимостей..."
    sudo apt-get update
    sudo apt-get install qrencode net-tools -y
}

# Клонирование репозитория
clone_repository() {
    if [ ! -d "awg_bot" ]; then
        echo "Клонирование репозитория..."
        git clone https://github.com/JB-SelfCompany/awg_bot.git
    else
        echo "Репозиторий уже существует."
    fi
    cd awg_bot || exit
}

# Настройка виртуального окружения
setup_venv() {
    echo "Настройка виртуального окружения..."
    python3.11 -m venv myenv
    source myenv/bin/activate
    pip install -r requirements.txt
}

# Создание systemd службы
create_service() {
    sudo bash -c "cat > /etc/systemd/system/$SERVICE_NAME.service" <<EOL
[Unit]
Description=AWG Telegram Bot
After=network.target

[Service]
User=$USER
WorkingDirectory=$(pwd)
ExecStart=$(pwd)/myenv/bin/python3.11 $(pwd)/bot_manager.py
Restart=always

[Install]
WantedBy=multi-user.target
EOL
    sudo systemctl daemon-reload
    sudo systemctl start $SERVICE_NAME
    sudo systemctl enable $SERVICE_NAME
}

# Ввод API токена
setup_api_token() {
    echo "Введите API токен бота, полученный от BotFather:"
    read -r api_token
    echo "BOT_TOKEN=\"$api_token\"" > .env
}

# Меню управления службой
service_menu() {
    echo "=== Статус службы $SERVICE_NAME ==="
    sudo systemctl status $SERVICE_NAME | grep Active

    echo "1. Остановить службу"
    echo "2. Перезапустить службу"
    echo "3. Удалить службу"
    echo "4. Выйти"
    read -p "Выберите действие: " action

    case $action in
        1) sudo systemctl stop $SERVICE_NAME ;;
        2) sudo systemctl restart $SERVICE_NAME ;;
        3) sudo systemctl stop $SERVICE_NAME
           sudo systemctl disable $SERVICE_NAME
           sudo rm /etc/systemd/system/$SERVICE_NAME.service
           sudo systemctl daemon-reload
           echo "Служба удалена." ;;
        4) exit 0 ;;
        *) echo "Некорректный ввод." ;;
    esac
}

# Главная логика
main() {
    if systemctl list-units --type=service | grep -q $SERVICE_NAME; then
        echo "Бот уже установлен как служба."
        service_menu
    else
        echo "Бот не установлен."
        read -p "Установить бот как службу? (y/n): " install_bot
        if [[ "$install_bot" == "y" ]]; then
            check_python
            check_git
            install_dependencies
            clone_repository
            setup_venv
            setup_api_token
            create_service
            echo "Установка завершена. Бот запущен и работает."
        else
            echo "Установка отменена."
        fi
    fi
}

# Запуск основной функции
main
```

**Comment by JB-SelfCompany** [comment]
https://github.com/JB-SelfCompany/awg_bot/commit/357b74b11ea6e20f785bf56fab29a0a1ae378fea 
Создал скрипт, сделал красивым. Функционал заявлен, как и просил.

**Comment by Ground-Zerro** [comment]
> Функционал заявлен, как и просил.

Симпатично. Функционально.
Спасибо.
