### ISSUE TITLE
Добавить поддержку pivpn

### ISSUE THREAD

**Issue by Ground-Zerro** [JB-SelfCompany/awg_bot#2]
Добавьте пожалуйста в бот поддержку работы с [pivpn](https://github.com/pivpn/pivpn).
У него конфиги хранятся немного в другом месте.

**Comment by JB-SelfCompany** [comment]
Не вижу необходимости в данной поддержке. 
Сервис малоизвестный, проще воспользоваться ванильным wg или awg.
