### ISSUE TITLE
Хотелки - улучшения

### ISSUE THREAD

**Issue by orlovnv** [JB-SelfCompany/awg_bot#3]
1. подчищать сообщения пользователя
2. центровать ответ бота или расширить ответ на всю ширину чата
3. свернуть ссылку для AmneziaVPN в кнопку, а то много букв и места много занимает

**Comment by JB-SelfCompany** [comment]
https://github.com/JB-SelfCompany/awg_bot/commit/44c296968528c206cfd24092915941aea774f7b0
1. Реализовал очистку сообщений
2. К сожалению, невозможно, в силу ограничений телеграмма
3. Сделал форматирование, теперь более аккуратно выглядит. Под кнопку реализовывать не стал. Игра не стоит свеч, так заморачиваться.
