### ISSUE TITLE
Ошибка при установке 

### ISSUE THREAD

**Issue by WolNe-R** [JB-SelfCompany/awg_bot#4]
![изображение_2024-12-01_154527427](https://github.com/user-attachments/assets/1d85625c-5e2d-43b5-9ee8-eb4777b54cb6)

Как можно пофиксить эту ошибку?
Не сильно разбираюсь в линуксе (

**Comment by ron-tayler** [comment]
Главное не ребутай сервак. Мы через это прошли XD

**Comment by ILMoroz** [comment]
Вы случаем в процессе установки консоль не закрывали ?
